server:
  port: 8090

spring:
  application:
    name: unit-testing

  datasource:
    url: jdbc:mysql://localhost:3307/unit_testing_db
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.ecommerce.unittesting: INFO
    org.springframework.boot.web.embedded: INFO
